# Forward Propagation

In [1]:
import numpy as np
import math
import pandas as pd

np.random.seed(101)

## **Create a NeuralNetwork class**

In [2]:
class NeuralNetwork():
    def __init__(self, dims):
        """ create an object which takes in a list of layer sizes and creates
        a list of weight matrices and a list of bias vectors, initialized to zeros. """
        self.layers = []
        self.bias_layers = []
        self.dims = dims
        for i in range(len(dims)-1):
            self.layers.append(np.zeros((dims[i], dims[i+1])))
            self.bias_layers.append(np.zeros(dims[i+1]))
        
    def randomize_weights(self, min1=-1, max1=1):
        self.layers = []
        self.bias_layers = []
        for i in range(len(self.dims)-1):
            self.layers.append(np.random.uniform(min1, max1, size = (self.dims[i], self.dims[i+1])))
            self.bias_layers.append(np.random.uniform(min1, max1, size = (1, self.dims[i+1])))
        """ store all random reals in the weight matrices and bias vectors, between min and max """

    def randomize_nice(self, min1=-10, max1=10):
        """ store all random ints in the weight matrices and bias vectors, between min and max"""
        self.layers = []
        self.bias_layers = []
        for i in range(len(self.dims)-1):
            self.layers.append(np.random.randint(size = (self.dims[i], self.dims[i+1]), low = min1, high = max1))
            self.bias_layers.append(np.random.randint(size = (1, self.dims[i+1]), low = min1, high = max1))
        
    def print_layers(self):
        for i in range(len(self.layers)):
            print("layer")
            print(self.layers[i])
            print("bias")
            print(self.bias_layers[i])
        """ print contents of each weight matrix and bias vector """
            
        

** Quick check of initializer **

In [3]:
nn = NeuralNetwork([2,5,3,2])
nn.print_layers()

layer
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
bias
[0. 0. 0. 0. 0.]
layer
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
bias
[0. 0. 0.]
layer
[[0. 0.]
 [0. 0.]
 [0. 0.]]
bias
[0. 0.]


In [4]:
nn.layers[0] = np.array([[-10,20,-20,50,30],[30,-20,10,-40,-20]])
nn.bias_layers[0] = np.array([[30,20,-10,20,30]])
nn.layers[1] = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0],[1,0,1]])
nn.bias_layers[1] = np.array([[20,-10,-10]])
nn.layers[2] = np.array([[10,0],[-10,20],[-30,0]])
nn.bias_layers[2] = np.array([[-5,5]])
nn.print_layers()

layer
[[-10  20 -20  50  30]
 [ 30 -20  10 -40 -20]]
bias
[[ 30  20 -10  20  30]]
layer
[[1 0 1]
 [0 0 1]
 [1 1 0]
 [0 1 0]
 [1 0 1]]
bias
[[ 20 -10 -10]]
layer
[[ 10   0]
 [-10  20]
 [-30   0]]
bias
[[-5  5]]


** Define sigmoid(x,k) with k default value=1 **

In [5]:
def sigmoid(x,k=1):
    if x < -500:
        return 0
    return 1/(1+math.exp(-k*x))
    
def sigmoid_prime(x,k=1):
    return (sigmoid(x) * (1-sigmoid(x)))

** Define step(x) **

In [6]:
def step(x):
    if x > 0: return 1
    return 0

In [7]:
def tenth(x):
    return x/10
def tenth_der(x):
    return 1/10

**Define forward_propagate(NN, x, A, verbose)**
  * This returns the (vector) output of feeding input vector "x" into Neural Net NN, with activation function A.
  * The 'verbose' flag tells whether to print the output of each layer. Default is False

In [8]:
def forward_propagate(NN, x, A, verbose = False):
    vector_A = np.vectorize(A)
    for i in range(len(NN.layers)):
        x = np.array(x)
        x = vector_A(np.dot(x, NN.layers[i]) + NN.bias_layers[i])
    if verbose == True:
        print(x)
        
    
    return x
        
        
    """ given neural net NN and input vector x, and activation function A,
    return the output of the final layer of the NN. If verbose if true,
    print output of each layer along the way"""

# Test Output

Check the following outputs against your code

** Set the numpy random seed to 101. Create a 2,4,2,5,2 Neural Network. Randomize its weights integers between -10 and 10 and print the layers **

In [9]:
np.random.seed(101)
nn = NeuralNetwork([2,4,2,5,2])
nn.randomize_nice()
nn.print_layers()

layer
[[ 1  7 -4  1]
 [ 5 -1  3 -2]]
bias
[[ -6  -2 -10   4]]
layer
[[-5  2]
 [-2  7]
 [ 9  5]
 [-2  9]]
bias
[[ 9 -8]]
layer
[[  2  -2   9   0   2]
 [  1 -10  -1  -1   5]]
bias
[[-2 -6  9 -7 -3]]
layer
[[ 0 -3]
 [-4  4]
 [-1  8]
 [-3 -3]
 [ 5  2]]
bias
[[-10   0]]


** Define an input vector [10,20] and propagate it through the NN above. Show the output of each layer. **

## x = [10,20]

forward_propagate(nn,x,tenth,verbose=True)

In [10]:
x=[10,20]
forward_propagate(nn,x,tenth,True)

[[ 0.7964 -2.7548]]


array([[ 0.7964, -2.7548]])

In [11]:
def back_propagate(NN, x, y, A, A_prime):
        outputs = []
        lamb = 100
        outputs.append(np.array(x))
        for i in range(len(NN.layers)): #Forward Propagation
            x = np.array(x)
            x = A(np.dot(x, NN.layers[i]) + NN.bias_layers[i])
            outputs.append(x)
        print(outputs)
        grad = (A_prime(1) * (y-x)) # Calculate error for final output
        grad_matrix = []
        grad_matrix.append(np.array(grad))
        for i in range(len(NN.layers)-1,0,-1):  # Calculates the rest of the gradients 
            arr = []
            for j in range(len(NN.layers[i])):
                arr.append(A_prime(1) * grad_matrix[i - len(NN.layers) + 1] @ NN.layers[i][j])
            grad_matrix.append(np.array(arr))
            print((grad_matrix[0],NN.layers[i]))
        print(grad_matrix)
        for i in range(len(NN.layers)):  #Update all of the other weights using gradient
            for j in range(len(NN.layers[i])):
                NN.layers[i][j] = NN.layers[i][j] + outputs[i][j] * lamb * grad_matrix[len(NN.layers)-i-1]
        NN.print_layers()            

In [12]:
nn = NeuralNetwork([3,2,2])
nn.layers[0] = [[4,-2], [0,1], [2,6]]
nn.layers[1] = [[2,3],[3,2]]
nn.print_layers()
back_propagate(nn, [10,20,30], [8,6], tenth, tenth_der)
b = np.array([.03,0]) @ np.array([-2,-1])
print(b)

layer
[[4, -2], [0, 1], [2, 6]]
bias
[0. 0.]
layer
[[2, 3], [3, 2]]
bias
[0. 0.]
[array([10, 20, 30]), array([10., 18.]), array([7.4, 6.6])]
(array([ 0.06, -0.06]), [[2, 3], [3, 2]])
[array([ 0.06, -0.06]), array([-0.006,  0.006])]
layer
[array([-2.,  4.]), array([-12.,  13.]), array([-16.,  24.])]
bias
[0. 0.]
layer
[array([ 62., -57.]), array([ 111., -106.])]
bias
[0. 0.]
-0.06


In [21]:
def back_propagate_matrix(NN, training_set, A, A_prime):
    epochs = 2000
    lamb = 1
    count = 1
    NN.randomize_weights()
    vector_A_prime = np.vectorize(A_prime)
    vector_A = np.vectorize(A)
    for e in range(epochs):
        for tup in training_set:
            x, y = tup
            outputs = []
            dots = []
            x = np.array([x])
            outputs.append(x)
            dots.append(x)
            for i in range(len(NN.layers)): #Forward Propagation
                dot = np.dot(x, NN.layers[i]) + NN.bias_layers[i]
                x = vector_A(dot)
                dots.append(dot)
                outputs.append(x)
            error = y-x
            delta = (vector_A_prime(outputs[-1]) * (y-x)) # Calculate error for final output
            delta_matrix = []
            delta_matrix.append(delta)
            for i in range(len(NN.layers)-1,0,-1):  # Calculates the rest of the gradients
                delta_matrix.append(np.multiply(vector_A_prime(dots[i]), np.matmul(delta_matrix[i - len(NN.layers) + 1], np.transpose(NN.layers[i]))))
            for i in range(len(NN.layers)):  #Update all of the other weights using gradient
                NN.layers[i] = NN.layers[i] + (np.transpose(outputs[i])) *  delta_matrix[len(NN.layers)-i-1] *  lamb
                NN.bias_layers[i] = NN.bias_layers[i] + lamb * delta_matrix[len(NN.layers)-i-1]
            count += 1
            if count % 500 == 0:
                print(count)
    correct = 0
    total = 0
    for tup in training_set:
        x,y = tup
        out = forward_propagate(NN,x, sigmoid, verbose = True)
        if np.argmax(y) == np.argmax(x):
            correct += 1
        total += 1
    return correct / total

In [22]:
nn = NeuralNetwork([2,4,1])
training_set = [(np.array([0,0]),np.array([0])), (np.array([0,1]),np.array([1])), (np.array([1,0]),np.array([1])),(np.array([1,1]),np.array([0]))]
back_propagate_matrix(nn, training_set, sigmoid, sigmoid_prime)

500
1000
1500
2000
2500
3000
3500
4000
4500
5000
5500
6000
6500
7000
7500
8000
[[0.00153353]]
[[0.99505487]]
[[0.99216954]]
[[0.01124973]]


0.75

In [ ]:
train = pd.read_csv("mnist_train.csv")
test = pd.read_csv("mnist_test.csv")
rows, col = train.shape


    



In [ ]:
training_set = []
for i in range(rows):
    row = train.iloc[i,:]
    out = row.iloc[0]
    encode = np.zeros((1,10))
    encode[0][out] = 1
    if i % 1000 == 0:
        print(i)
    tup = (row.iloc[1:785],encode)
    training_set.append(tup)
test_set = []
for i in range(test.shape[0]):
    row = test.iloc[i,:]
    out = row.iloc[0]
    encode = np.zeros((1,10))
    encode[0][out] = 1
    if i % 1000 == 0:
        print(i)
    tup = (row.iloc[1:785],encode)
    test_set.append(tup)

In [ ]:
back_propagate_matrix(nn, training_set, sigmoid, sigmoid_prime)